"""Fix Models

Revision ID: 437cc9bee8cd
Revises: 6a14e885d83e
Create Date: 2022-08-14 20:58:35.936512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437cc9bee8cd'
down_revision = '6a14e885d83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('artists', 'website_link')
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website')
    op.add_column('artists', sa.Column('website_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
