"""Migration After Implement Genre Model

Revision ID: 822cdd9d4e96
Revises: 3bec497197fc
Create Date: 2022-08-14 18:08:45.490620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822cdd9d4e96'
down_revision = '3bec497197fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('artist_genre_association',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.create_table('venue_genre_association',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.create_unique_constraint(None, 'artists', ['id'])
    op.drop_column('artists', 'genres')
    op.create_unique_constraint(None, 'shows', ['id'])
    op.create_unique_constraint(None, 'venues', ['id'])
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'shows', type_='unique')
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artists', type_='unique')
    op.drop_table('venue_genre_association')
    op.drop_table('artist_genre_association')
    op.drop_table('genres')
    # ### end Alembic commands ###
